stages:
  - codestyle
  - security

flake8_lint:
  stage: codestyle
  image: python:3.11
  before_script:
    - pip install flake8
  script:
    - flake8 --config=.flake8
  only:
    changes:
      - '**/*.py'

bandit_lint:
  stage: security
  image: python:3.11
  before_script:
    - pip install bandit
  script:
    - bandit -r .
